name: New Beta GO Release

on:
  push:
    branches:
      - production

# Only allow the most recent run of beta release to complete, if multiple are queued.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call-build-frontend:
    uses: ./.github/workflows/build-frontend.yml
    secrets:
      NX_GOOGLE_CLIENT_ID: ${{ secrets.NX_GOOGLE_CLIENT_ID }}
    with:
      frontend_name: 'frontend'
      deployment_name: 'beta'
      show_dev_components: true
