name: Build Frontend
run-name: Build frontend of ${{ inputs.frontend_name }} for ${{ inputs.deployment_name }} - ${{ github.event.pull_request.merge_commit_sha }}

on:
  workflow_call:
    inputs:
      frontend_name:
        description: 'Frontend type to build. Can be `frontend`, `sr-frontend`, or `zzz-frontend`.'
        type: string
        required: true
      deployment_name:
        description: 'Name for the deployment. This will determine the URL. If you choose a name that is already deployed, it will overwrite that deployment.'
        type: string
        default: 'production'
      show_dev_components:
        description: 'Flag to show components typically only shown in development mode, for experimental or in-progress features.'
        type: boolean
        default: false
      nested_deployments:
        description: 'When true, the deployment will be nested in a sub-folder corresponding to the frontend_name. When false, the deployment will sit in the repo root folder, which means you can only have 1 deployment active at a time'
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: 'build'
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
          submodules: false
      - name: Checkout GenshinData submodule
        run: |
          git submodule sync -- libs/gi/dm/GenshinData
          git submodule update --init --depth=1 -- libs/gi/dm/GenshinData
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Yarn install
        run: |
          yarn install --immutable
      - name: Setup .env
        run: |
          printf '%s\n' "$ENVFILE" > apps/frontend/.env.local
          if [ -n "$NX_GOOGLE_CLIENT_ID" ]; then
            echo "NX_GOOGLE_CLIENT_ID=$NX_GOOGLE_CLIENT_ID" >> apps/frontend/.env.local
          fi
        env:
          ENVFILE: ${{ vars.ENVFILE }}
          NX_GOOGLE_CLIENT_ID: ${{ secrets.NX_GOOGLE_CLIENT_ID }}
      - name: Build frontend
        run: |
          echo $NX_SHOW_DEV_COMPONENTS
          yarn run nx run ${{inputs.frontend_name}}:build:production
        env:
          NX_URL_GITHUB_GO_CURRENT_VERSION: "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          NX_DAEMON: false
          NX_SHOW_DEV_COMPONENTS: ${{inputs.show_dev_components}}
          NX_GOOGLE_CLIENT_ID: ${{ secrets.NX_GOOGLE_CLIENT_ID }}
      - name: echos
        run: |
          echo ${{inputs.frontend_name}} > frontend_name
          echo ${{inputs.deployment_name}} > deployment_name
          echo ${{inputs.nested_deployments}} > nested_deployments
          echo $(git rev-parse HEAD) > ref
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: frontend_build
          path: |
            dist/apps/${{inputs.frontend_name}}
            frontend_name
            deployment_name
            nested_deployments
            ref
